# Generated by Django 5.1.3 on 2024-11-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0002_booklist_user_alter_booklist_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='user',
            new_name='owner',
        ),
    ]
