# Generated by Django 5.1.2 on 2024-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0001_initial'),
        ('users', '0002_alter_customuser_booklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='booklist',
            field=models.ManyToManyField(related_name='lists', to='booklists.booklist'),
        ),
    ]
