# Generated by Django 5.1.2 on 2024-11-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='booklist',
        ),
    ]
