# Generated by Django 5.1.3 on 2024-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0001_initial'),
        ('users', '0006_customuser_booklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='booklist',
            field=models.ManyToManyField(blank=True, related_name='booklists', to='booklists.booklist'),
        ),
    ]
