# Generated by Django 5.1.3 on 2024-11-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0001_initial'),
        ('users', '0007_alter_customuser_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='booklist',
        ),
        migrations.AddField(
            model_name='customuser',
            name='booklist',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booklists', to='booklists.booklist'),
            preserve_default=False,
        ),
    ]
