# Generated by Django 5.1.3 on 2024-11-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_booklist_customuser_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='booklist',
        ),
    ]
