services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: booktracker
    command: uv run python manage.py runserver 0.0.0.0:8000
    networks:
      - default
    depends_on:
      - redis

  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - default
  celery:
    build:
      context: .
    command: uv run celery -A booktracker worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - default
networks:
  default:
    driver: bridge
