# Generated by Django 5.1.3 on 2024-11-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_book_author_book'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='authors', to='books.book'),
        ),
    ]
