# Generated by Django 5.1.3 on 2024-11-18 10:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_book'),
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='books_book_search__c24b82_gin'),
        ),
    ]
