# Generated by Django 5.1.3 on 2024-11-19 11:06

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
