# Generated by Django 5.1.3 on 2024-11-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_search_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_search__c24b82_gin',
        ),
        migrations.RemoveField(
            model_name='book',
            name='search_vector',
        ),
    ]
